### ISSUE TITLE
Dernek üye (kullanıcı) geliştirmesi

### ISSUE THREAD

**Issue by cgaziogluu** [alicangunduz/dernek-yonetim#11]
dernek üyeleri sisteme giriş yapsalar oradan aidat bilgilerini görseler dilerseler bağışta bulunsalar yada aidatlarını Paytr yada izyco gibi entegrasyonlar ile ödeyebilse süper sistem olurdu. Emeğinize sağlık.

**Comment by alicangunduz** [comment]
İlginiz için çok teşekkür ederim. Bu yazılımı gönüllülük esasıyla geliştirmiştim, ancak şu anda aktif olarak üzerinde çalıştığım bir proje değil. Ayrıca, şu an sıkça kullandığım bir programlama dili de değil. Tekrar teşekkür ederim.
